interpolate:
  ndarray_1d_from_grid:
    MockGridLikeIteratorObj: true
  ndarray_2d_from_grid:
    MockGridLikeIteratorObj: true
# Certain light and mass profile calculations become ill defined at (0.0, 0.0) or close to this value. This can lead
# to numerical issues in the calculation of the profile, for example a np.nan may arise, crashing the code. 
  
# To avoid this, we set a minimum value for the radial coordinate of the profile. If the radial coordinate is below 
# this value, it is rounded up to this value. This ensures that the profile cannot receive a radial coordinate of 0.0.

# For example, if an input grid coordinate has a radial coordinate of 1e-12, for most profiles this will be rounded up
# to radial_minimum=1e-08. This is a small enough value that it should not impact the results of the profile calculation.

radial_minimum:
  radial_minimum:
    MockGridRadialMinimum: 2.5


# Over sampling is an important numerical technique, whereby light profiles images are evaluated on a higher resolution
# grid than the image data to ensure the calculation is accurate.

# By default, a user does not specify the over sampling factor, and a default over sampling scheme is used for each
# profile. This scheme first goes to the centre of the profile, and computes circles with certain radial values
# (e.g. radii). It then assigns an over sampling `sub_size` to each circle, where the central circles have the highest
# over sampling factor and the outer circles have the lowest.

# The size of the circles that are appropriate for determining the over sampling factor are dependent on the resolution
# of the grid. For a high resolution grid (e.g. low pixel scale), a smaller circle central circle is necessary to
# over sample the profile accurately. The config file below therefore specifies the "radial factors" used for
# automatically determining the over sampling factors for each profile, which is the factor the pixel scale is multiplied
# by to determine the circle size.

# The config entry below defines the default over sampling factor for each profile, where:

# radial_factor_list: The factors that are multiplied by the pixel scale to determine the circle size that is used.
# sub_size_list: The over sampling factor that is used for each circle size.

# For the default entries below, oversampling of degree 32 x 32 is used within a circle of radius 3.01 x pixel scale,
# 4 x 4 within a circle of radius 10.01 x pixel scale and 2 x 2 for all pixels outside of this radius.

# For unit tests, we disable this feature by setting the over sampling factors to 1.0 and the sub sizes to 1.

over_sampling:
  radial_factor_list:
    MockGrid1DLikeObj: [1.0]
    MockGrid2DLikeObj: [1.0]
    MockGridLikeIteratorObj: [1.0]
    MockGridRadialMinimum: [1.0]
  sub_size_list:
    MockGrid1DLikeObj: [1, 1]
    MockGrid2DLikeObj: [1, 1]
    MockGridLikeIteratorObj: [1, 1]
    MockGridRadialMinimum: [1, 1]